"use client";

import {useEffect,useMemo,useState} from "react";

type Trade={strategy:string;date:string;status:string;symbol:string;sector:string;entryTime:string;entryPrice:number|null;exitTime:string;exitPrice:number|null;net:number|null;spy:number|null;breadth?:number|null};
type Strategy={id:string;label:string;short:string;color:string;phase:"frozen"|"challenger";signal:string;entry:string;exit:string;explanation:string[];sessions:number;trades:number;mean:number|null;median:number|null;winRate:number|null;compounded:number|null;drawdown:number|null;status:string};
type EquityPoint={date:string;values:Record<string,number>};
type DashboardData={generatedAt:string;headline:string;strategies:Strategy[];trades:Trade[];equity:EquityPoint[]};
const fallback:DashboardData={generatedAt:"Awaiting first forward session",headline:"Forward paper validation",strategies:[],trades:[],equity:[]};
const pct=(v:number|null,d=2)=>v==null?"—":`${v>=0?"+":""}${(v*100).toFixed(d)}%`;
const money=(v:number,d=0)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:d}).format(v);

function ModelHelp({strategy,onClose}:{strategy:Strategy;onClose:()=>void}){return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close explanation">×</button><p className="eyebrow">{strategy.phase.toUpperCase()} MODEL</p><h2 id="help-title">{strategy.label}</h2><div className="schedule-strip"><span>Signal <b>{strategy.signal}</b></span><span>Entry <b>{strategy.entry}</b></span><span>Exit <b>{strategy.exit}</b></span></div><ul>{strategy.explanation.map(x=><li key={x}>{x}</li>)}</ul><p className="help-note">Paper validation only. Each model keeps its own audit trail and cannot place orders.</p></section></div>}

function EquityChart({equity,strategies,capital}:{equity:EquityPoint[];strategies:Strategy[];capital:number}){
 const baseline:EquityPoint={date:"Day 0",values:Object.fromEntries(strategies.map(s=>[s.id,1]))};
 const points=[baseline,...equity]; const values=points.flatMap(p=>strategies.map(s=>p.values[s.id]??1)); const min=Math.min(1,...values),max=Math.max(1,...values),span=Math.max(.006,max-min);
 const coords=(s:Strategy)=>points.map((p,i)=>({x:i/Math.max(points.length-1,1)*100,y:94-((p.values[s.id]??1)-min)/span*82}));
 return <article className="equity-card"><div className="section-head"><div><p className="eyebrow">VIRTUAL ALLOCATION</p><h2>Growth from day zero</h2></div><span>Start <b>{money(capital)}</b></span></div><div className="chart-legend">{strategies.map(s=><span key={s.id}><i style={{background:s.color}}/>{s.short} {money(capital*(points.at(-1)?.values[s.id]??1))}</span>)}</div><div className="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Virtual allocation performance from day zero"><line x1="0" y1="12" x2="100" y2="12"/><line x1="0" y1="53" x2="100" y2="53"/><line x1="0" y1="94" x2="100" y2="94"/>{strategies.map(s=>{const c=coords(s);return <g key={s.id}><polyline points={c.map(p=>`${p.x},${p.y}`).join(" ")} style={{stroke:s.color}}/>{c.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="1.5" style={{fill:s.color}}/>)}</g>})}</svg></div><div className="chart-labels"><span>Day 0 · {money(capital)}</span><span>{equity.length?equity.at(-1)?.date:"Waiting for session 1"}</span></div></article>
}

function ModelCard({s,onHelp}:{s:Strategy;onHelp:()=>void}){return <article className="model" style={{"--accent":s.color} as React.CSSProperties}><div className="model-title"><span/><div><small>{s.short} · {s.phase}</small><h3>{s.label}</h3></div><button className="help-button" onClick={onHelp} aria-label={`Explain ${s.label}`}>?</button></div><div className="model-status"><b>{s.status}</b><span>{s.sessions} sessions</span></div><div className="schedule"><span>{s.signal}<small>signal</small></span><span>{s.entry}<small>entry</small></span><span>{s.exit}<small>exit</small></span></div><div className="metrics"><div><small>TRADES</small><strong>{s.trades}</strong></div><div><small>AVG</small><strong>{pct(s.mean,3)}</strong></div><div><small>RETURN</small><strong>{pct(s.compounded)}</strong></div><div><small>DRAW­DOWN</small><strong>{pct(s.drawdown)}</strong></div></div><div className="progress"><span style={{width:`${Math.min(100,s.trades/60*100)}%`}}/></div><p>{s.trades<30?`${30-s.trades} trades to first review`:`${Math.max(0,60-s.trades)} trades to preferred review`}</p></article>}

function History({strategy,trades}:{strategy:Strategy;trades:Trade[]}){return <article className="history-card"><div className="section-head"><div><p className="eyebrow" style={{color:strategy.color}}>AUDIT TRAIL · {strategy.short}</p><h2>{strategy.label}</h2></div><span>{trades.length} decisions</span></div><div className="table"><div className="tr th"><span>Date</span><span>Position</span><span>Entry</span><span>Exit</span><span>Status</span><span>Return</span><span>vs SPY</span></div>{trades.slice(0,25).map((t,i)=>{const position=t.status==="NO_TRADE"?"NO POSITION":t.exitPrice!=null?"SOLD":"OPEN";const relative=t.net!=null&&t.spy!=null?t.net-t.spy:null;return <div className="tr" key={`${t.date}-${i}`}><span data-label="Date">{t.date}</span><span data-label="Position"><b>{t.symbol||"Cash"}</b>{t.sector&&<small>{t.sector}</small>}</span><span data-label="Entry">{t.entryPrice!=null?<>{money(t.entryPrice,2)}<small>{t.entryTime} ET</small></>:"—"}</span><span data-label="Exit">{t.exitPrice!=null?<>{money(t.exitPrice,2)}<small>{t.exitTime} ET</small></>:"—"}</span><span data-label="Status"><b className={`position-badge ${position.toLowerCase().replace(" ","-")}`}>{position}</b></span><span data-label="Return" className={t.net==null?"":t.net>=0?"up":"down"}>{pct(t.net,3)}</span><span data-label="vs SPY">{pct(relative,3)}</span></div>})}{!trades.length&&<div className="empty"><b>No forward decisions yet.</b><span>This model will show entries, exits, position status and returns here once prospective tracking begins.</span></div>}</div></article>}

export default function Home(){
 const [data,setData]=useState(fallback),[capital,setCapital]=useState(10000),[help,setHelp]=useState<Strategy|null>(null);
 useEffect(()=>{fetch("./data/dashboard.json",{cache:"no-store"}).then(r=>r.ok?r.json():fallback).then(setData).catch(()=>setData(fallback))},[]);
 const histories=useMemo(()=>Object.fromEntries(data.strategies.map(s=>[s.id,data.trades.filter(t=>t.strategy===s.id)])),[data]);
 const frozen=data.strategies.filter(s=>s.phase==="frozen"),challengers=data.strategies.filter(s=>s.phase==="challenger");
 return <main><header className="topbar"><div className="brand"><span className="brandmark">A</span><div><b>Atlas Signal Lab</b><small>Prospective paper validation</small></div></div><div className="status"><span/>Paper only · no live orders</div></header>
 <section className="hero"><div><p className="eyebrow">SIRS · MODEL LAB</p><h1>Signals tracked.<br/><em>Rules kept honest.</em></h1><p className="lede">Frozen models and research challengers, separated clearly. Every entry, exit, return and decision to hold cash stays in its own audit trail.</p></div><div className="next-card"><div className="next-head"><span>DECISION WINDOWS</span><b>ET</b></div><div className="decision-times"><b>11:00</b><span>V1 · V2 · C2</span><b>12:00</b><span>C1 · C3</span></div><p>Same-day models exit near 15:55. Overnight challengers exit at the next regular-session open.</p><div className="line"><span>Latest refresh</span><b>{data.generatedAt}</b></div></div></section>
 <section className="model-group"><div className="group-head"><p className="eyebrow">FROZEN VALIDATION</p><span>Rules cannot change during collection</span></div><div className="models">{frozen.map(s=><ModelCard key={s.id} s={s} onHelp={()=>setHelp(s)}/>)}</div></section>
 <section className="model-group"><div className="group-head"><p className="eyebrow challenger-label">RESEARCH CHALLENGERS</p><span>Tracked separately · not promoted</span></div><div className="models challengers">{challengers.map(s=><ModelCard key={s.id} s={s} onHelp={()=>setHelp(s)}/>)}</div></section>
 <section className="allocation-section"><label className="capital-control">Virtual starting allocation <b>{money(capital)}</b><input type="range" min="1000" max="100000" step="1000" value={capital} onChange={e=>setCapital(Number(e.target.value))}/></label><EquityChart equity={data.equity} strategies={data.strategies} capital={capital}/></section>
 <section className="histories">{data.strategies.map(s=><History key={s.id} strategy={s} trades={histories[s.id]||[]}/>)}</section><footer><b>Paper validation only.</b> Historical research is not prospective proof. This interface is read-only and cannot place orders.</footer>{help&&<ModelHelp strategy={help} onClose={()=>setHelp(null)}/>}</main>
}
