/* eslint-disable jsx-a11y/no-noninteractive-element-interactions, no-loss-of-precision */
"use client";

import {useEffect,useMemo,useState} from "react";

type Trade={strategy:string;date:string;status:string;reason:string;symbol:string;sector:string;entryTime:string;entryPrice:number|null;exitTime:string;exitPrice:number|null;net:number|null;spy:number|null;breadth?:number|null};
type Strategy={id:string;label:string;short:string;color:string;phase:"frozen"|"challenger";signal:string;entry:string;exit:string;explanation:string[];sessions:number;trades:number;noOps:number;mean:number|null;median:number|null;winRate:number|null;compounded:number|null;drawdown:number|null;status:string};
type EquityPoint={date:string;values:Record<string,number>};
type DashboardData={generatedAt:string;headline:string;strategies:Strategy[];trades:Trade[];equity:EquityPoint[]};
type ProspectiveStatus={strategy:string;classification:string;state:string;last_session:string|null;pending_entries:number;open_positions:number;completed_trades:number;trades_remaining:number;calendar_gate_date:string;days_remaining:number;aggregate_results_locked:boolean;errors:string[]};
type ResearchModel={model:string;label:string;historical_screen:string;deployment_verdict:string;annualized_return:number;max_drawdown:number;ending_10000:number;note:string};
type FailedFamily={name:string;status:string;tested:string;result:string;why:string};
type ResearchResult={title:string;conclusion:string;period:string;months:number;price_source:string;universe:string;models:ResearchModel[];gates:{gate:string;passed:boolean}[];failed_families:FailedFamily[];whole_share:{ending_10000:number;trades:number;gross_turnover_dollars:number;sleeves:number}};
const fallback:DashboardData={generatedAt:"Awaiting first forward session",headline:"Forward paper validation",strategies:[],trades:[],equity:[]};
const pct=(v:number|null,d=2)=>v==null?"—":`${v>=0?"+":""}${(v*100).toFixed(d)}%`;
const money=(v:number,d=0)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:d}).format(v);

function FailedFamilyArchive({families}:{families:FailedFamily[]}){return <section className="failed-archive"><div className="section-head"><div><p className="eyebrow">ADDITIONAL COMPLETED RESEARCH</p><h2>Other models that did not advance</h2></div><span>{families.length} tested families</span></div><div className="failed-grid">{families.map(f=><article key={f.name}><div className="failed-title"><h3>{f.name}</h3><i>{f.status}</i></div><dl><div><dt>TESTED</dt><dd>{f.tested}</dd></div><div><dt>RESULT</dt><dd>{f.result}</dd></div><div><dt>WHY IT STOPPED</dt><dd>{f.why}</dd></div></dl></article>)}</div><p className="archive-note">These are completed historical or feasibility studies—not active models. “Exploratory only” means the old setup was not strong enough to support a deployment decision.</p></section>}

function ModelHelp({strategy,onClose}:{strategy:Strategy;onClose:()=>void}){return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close explanation">×</button><p className="eyebrow">{strategy.phase.toUpperCase()} MODEL</p><h2 id="help-title">{strategy.label}</h2><div className="schedule-strip"><span>Signal <b>{strategy.signal}</b></span><span>Entry <b>{strategy.entry}</b></span><span>Exit <b>{strategy.exit}</b></span></div><ul>{strategy.explanation.map(x=><li key={x}>{x}</li>)}</ul><p className="help-note">Paper validation only. Each model keeps its own audit trail and cannot place orders.</p></section></div>}

function EquityChart({equity,strategies,capital}:{equity:EquityPoint[];strategies:Strategy[];capital:number}){
 const baseline:EquityPoint={date:"Day 0",values:Object.fromEntries(strategies.map(s=>[s.id,1]))};
 const points=[baseline,...equity]; const values=points.flatMap(p=>strategies.map(s=>p.values[s.id]??1)); const min=Math.min(1,...values),max=Math.max(1,...values),span=Math.max(.006,max-min);
 const coords=(s:Strategy)=>points.map((p,i)=>({x:i/Math.max(points.length-1,1)*100,y:94-((p.values[s.id]??1)-min)/span*82}));
 return <article className="equity-card"><div className="section-head"><div><p className="eyebrow">VIRTUAL ALLOCATION</p><h2>Growth from day zero</h2></div><span>Start <b>{money(capital)}</b></span></div><div className="chart-legend">{strategies.map(s=><span key={s.id}><i style={{background:s.color}}/>{s.short} {money(capital*(points.at(-1)?.values[s.id]??1))}</span>)}</div><div className="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Virtual allocation performance from day zero"><line x1="0" y1="12" x2="100" y2="12"/><line x1="0" y1="53" x2="100" y2="53"/><line x1="0" y1="94" x2="100" y2="94"/>{strategies.map(s=>{const c=coords(s);return <g key={s.id}><polyline points={c.map(p=>`${p.x},${p.y}`).join(" ")} style={{stroke:s.color}}/>{c.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="1.5" style={{fill:s.color}}/>)}</g>})}</svg></div><div className="chart-labels"><span>Day 0 · {money(capital)}</span><span>{equity.length?equity.at(-1)?.date:"Waiting for session 1"}</span></div></article>
}

function ModelCard({s,onHelp}:{s:Strategy;onHelp:()=>void}){return <article className="model" style={{"--accent":s.color} as React.CSSProperties}><div className="model-title"><span/><div><small>{s.short} · {s.phase}</small><h3>{s.label}</h3></div><button className="help-button" onClick={onHelp} aria-label={`Explain ${s.label}`}>?</button></div><div className="model-status"><b>{s.status}</b><span>{s.sessions} sessions</span></div><div className="schedule"><span>{s.signal}<small>signal</small></span><span>{s.entry}<small>entry</small></span><span>{s.exit}<small>exit</small></span></div><div className="metrics"><div><small>TRADES</small><strong>{s.trades}</strong></div><div className="no-op-metric"><small>NO OPS</small><strong>{s.noOps??0}</strong></div><div><small>AVG</small><strong>{pct(s.mean,3)}</strong></div><div><small>RETURN</small><strong>{pct(s.compounded)}</strong></div><div><small>DRAW­DOWN</small><strong>{pct(s.drawdown)}</strong></div></div><div className="progress"><span style={{width:`${Math.min(100,s.trades/60*100)}%`}}/></div><p>{s.trades<30?`${30-s.trades} trades to first review`:`${Math.max(0,60-s.trades)} trades to preferred review`}</p></article>}

function History({strategy,trades}:{strategy:Strategy;trades:Trade[]}){return <article className="history-card"><div className="section-head"><div><p className="eyebrow" style={{color:strategy.color}}>AUDIT TRAIL · {strategy.short}</p><h2>{strategy.label}</h2></div><span>{trades.length} decisions</span></div><div className="table"><div className="tr th"><span>Date</span><span>Position</span><span>Entry</span><span>Exit</span><span>Status</span><span>Return</span><span>vs SPY</span></div>{trades.slice(0,25).map((t,i)=>{const position=t.status==="NO_TRADE"?"NO OP":t.exitPrice!=null?"SOLD":"OPEN";const relative=t.net!=null&&t.spy!=null?t.net-t.spy:null;return <div className="tr" key={`${t.date}-${i}`}><span data-label="Date">{t.date}</span><span data-label="Position"><b>{t.symbol||"Cash"}</b>{t.sector&&<small>{t.sector}</small>}</span><span data-label="Entry">{t.entryPrice!=null?<>{money(t.entryPrice,2)}<small>{t.entryTime} ET</small></>:"—"}</span><span data-label="Exit">{t.exitPrice!=null?<>{money(t.exitPrice,2)}<small>{t.exitTime} ET</small></>:"—"}</span><span data-label="Status"><b className={`position-badge ${position.toLowerCase().replace(" ","-")}`}>{position}</b>{t.reason&&<small className="decision-reason">{t.reason}</small>}</span><span data-label="Return" className={t.net==null?"":t.net>=0?"up":"down"}>{pct(t.net,3)}</span><span data-label="vs SPY">{pct(relative,3)}</span></div>})}{!trades.length&&<div className="empty"><b>No forward decisions yet.</b><span>This model will show entries, exits, position status and returns here once prospective tracking begins.</span></div>}</div></article>}

function ResearchScoreboard({result,capital}:{result:ResearchResult;capital:number}){return <section className="research-section"><div className="research-verdict"><div><p className="eyebrow">COMPLETED REPLICATION · {result.period}</p><span className="reject-badge">REJECTED FOR DEPLOYMENT</span><h2>{result.title}</h2><p>{result.conclusion}</p></div><div className="verdict-word">FAIL<small>DO NOT IMPLEMENT</small></div></div><div className="research-summary"><div><small>MONTHLY COHORTS</small><strong>{result.months}</strong></div><div><small>PRIMARY</small><strong>{money(capital*2.6875893203809064)}</strong><span>fractional research curve</span></div><div><small>WHOLE-SHARE</small><strong>{money(capital*(result.whole_share.ending_10000/10000))}</strong><span>capital-constrained</span></div><div><small>SPY</small><strong>{money(capital*2.361617705339653)}</strong><span>same 90 months</span></div></div><div className="gate-list">{result.gates.map(g=><div key={g.gate} className={g.passed?"gate-pass":"gate-fail"}><b>{g.passed?"PASS":"FAIL"}</b><span>{g.gate}</span></div>)}</div><article className="scoreboard-card"><div className="section-head"><div><p className="eyebrow">EVERY TESTED SCENARIO</p><h2>What {money(capital)} would become</h2></div><span>Costs and dividends included</span></div><div className="research-table"><div className="rr rr-head"><span>Model</span><span>History</span><span>Deploy</span><span>Annual</span><span>Drawdown</span><span>Ending value</span></div>{result.models.map(m=><div className="rr" key={m.model}><span data-label="Model"><b>{m.label}</b><small>{m.note}</small></span><span data-label="History"><i className={`result-pill ${m.historical_screen.toLowerCase()}`}>{m.historical_screen}</i></span><span data-label="Deploy"><i className={`result-pill ${m.deployment_verdict.toLowerCase()}`}>{m.deployment_verdict}</i></span><span data-label="Annual">{pct(m.annualized_return)}</span><span data-label="Drawdown" className="down">{pct(m.max_drawdown)}</span><span data-label="Ending value"><b>{money(capital*(m.ending_10000/10000))}</b></span></div>)}</div></article><p className="method-note"><b>Method:</b> {result.price_source}. {result.universe} No model was activated; existing forward monitors are unchanged.</p></section>}

export default function Home(){
 const [data,setData]=useState(fallback),[capital,setCapital]=useState(10000),[help,setHelp]=useState<Strategy|null>(null),[prospective,setProspective]=useState<ProspectiveStatus|null>(null),[research,setResearch]=useState<ResearchResult|null>(null),[tab,setTab]=useState<"lab"|"failed">("lab");
 useEffect(()=>{fetch("./data/dashboard.json",{cache:"no-store"}).then(r=>r.ok?r.json():fallback).then(setData).catch(()=>setData(fallback))},[]);
 useEffect(()=>{fetch("./data/k_prospective_status.json",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setProspective).catch(()=>setProspective(null))},[]);
 useEffect(()=>{fetch("./data/momentum-validation.json",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setResearch).catch(()=>setResearch(null))},[]);
 const histories=useMemo(()=>Object.fromEntries(data.strategies.map(s=>[s.id,data.trades.filter(t=>t.strategy===s.id)])),[data]);
 const frozen=data.strategies.filter(s=>s.phase==="frozen"),challengers=data.strategies.filter(s=>s.phase==="challenger");
 const ranked=data.strategies.filter(s=>s.trades>0&&s.compounded!=null).sort((a,b)=>(b.compounded??-Infinity)-(a.compounded??-Infinity));const winner=ranked[0];const tied=winner?ranked.filter(s=>s.compounded===winner.compounded).length:0;
 return <main className={tab==="failed"?"failed-view":"lab-view"}><header className="topbar"><div className="brand"><span className="brandmark">A</span><div><b>Atlas Signal Lab</b><small>Prospective paper validation</small></div></div><nav className="view-tabs" aria-label="Dashboard sections"><button className={tab==="lab"?"active":""} onClick={()=>setTab("lab")}>Live model lab</button><button className={tab==="failed"?"active":""} onClick={()=>setTab("failed")}>Failed models <b>{research?.failed_families?.length??0}</b></button></nav><div className="status"><span/>Paper only · no live orders</div></header>{research&&tab==="failed"&&<><ResearchScoreboard result={research} capital={capital}/><FailedFamilyArchive families={research.failed_families??[]}/></>} 
 <section className="hero"><div><p className="eyebrow">SIRS · MODEL LAB</p><h1>Signals tracked.<br/><em>Rules kept honest.</em></h1><p className="lede">Frozen models and research challengers, separated clearly. Every entry, exit, return and decision to hold cash stays in its own audit trail.</p></div><div className="next-card"><div className="next-head"><span>DECISION WINDOWS</span><b>ET</b></div><div className="decision-times"><b>11:00</b><span>V1 · V2 · C2 · C5</span><b>12:00</b><span>C1 · C3 · C4 · C6</span></div><p>Same-day models exit near 15:55. Overnight challengers exit at the next regular-session open.</p><div className="line"><span>Latest refresh</span><b>{data.generatedAt}</b></div></div></section>
 <section className="winner-card" style={{"--winner":winner?.color??"#49d9a0"} as React.CSSProperties}><div className="winner-copy"><p className="eyebrow">PROVISIONAL WINNING MODEL</p>{winner?<><span className="winner-kicker">{tied>1?`${tied}-way tie · showing ${winner.short}`:`Current leader · ${winner.short}`}</span><h2>{winner.label}</h2><div className="winner-return">{pct(winner.compounded,2)}</div><p>Cumulative prospective return across {winner.trades} completed {winner.trades===1?"trade":"trades"}. Leadership can change as evidence accumulates.</p></>:<><h2>Waiting for a completed trade</h2><div className="winner-return">—</div><p>A model becomes eligible after its first completed prospective trade.</p></>}</div><div className="winner-value"><span>THEORETICAL VALUE</span><strong>{money(capital*(1+(winner?.compounded??0)))}</strong><small>from {money(capital)} starting capital</small><label>Starting capital<div className="money-input"><span>$</span><input aria-label="Starting capital" type="number" min="100" step="100" value={capital} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))setCapital(Math.max(0,v))}} onBlur={()=>setCapital(Math.max(100,capital||10000))}/></div><input aria-label="Starting capital slider" type="range" min="1000" max="250000" step="1000" value={Math.min(250000,Math.max(1000,capital))} onChange={e=>setCapital(Number(e.target.value))}/></label></div></section>
 {prospective&&<section className="prospective-card"><div className="prospective-head"><div><p className="eyebrow">FORWARD-ONLY PAPER MONITOR</p><h2>Frozen K · Confirmed reclaim</h2><span className="mixed-badge">{prospective.classification.replaceAll("_"," ")}</span></div><div className="lock-badge">Aggregate results locked</div></div><p className="prospective-copy">This monitor cannot backfill earlier trades. Returns, win rate and comparisons stay hidden until both evaluation gates are met and opening them is explicitly authorized.</p><div className="ops-grid"><div><small>STATE</small><strong>{prospective.state.replaceAll("_"," ")}</strong></div><div><small>COMPLETED</small><strong>{prospective.completed_trades} / 100</strong></div><div><small>OPEN</small><strong>{prospective.open_positions}</strong></div><div><small>PENDING</small><strong>{prospective.pending_entries}</strong></div><div><small>TRADES LEFT</small><strong>{prospective.trades_remaining}</strong></div><div><small>TIME LEFT</small><strong>{prospective.days_remaining} days</strong></div></div><div className="gate-track"><span style={{width:`${Math.min(100,prospective.completed_trades)}%`}}/></div><div className="prospective-foot"><span>Calendar gate: <b>{prospective.calendar_gate_date}</b></span><span>Last session: <b>{prospective.last_session??"Waiting for Aug 17"}</b></span></div>{prospective.errors.length>0&&<div className="monitor-error">Data issue recorded: {prospective.errors[0]}</div>}</section>}
 <section className="model-group"><div className="group-head"><p className="eyebrow">FROZEN VALIDATION</p><span>Rules cannot change during collection</span></div><div className="models">{frozen.map(s=><ModelCard key={s.id} s={s} onHelp={()=>setHelp(s)}/>)}</div></section>
 <section className="model-group"><div className="group-head"><p className="eyebrow challenger-label">RESEARCH CHALLENGERS</p><span>Tracked separately · not promoted</span></div><div className="models challengers">{challengers.map(s=><ModelCard key={s.id} s={s} onHelp={()=>setHelp(s)}/>)}</div></section>
 <section className="allocation-section"><EquityChart equity={data.equity} strategies={data.strategies} capital={capital}/></section>
 <section className="histories">{data.strategies.map(s=><History key={s.id} strategy={s} trades={histories[s.id]||[]}/>)}</section><footer><b>Paper validation only.</b> Historical research is not prospective proof. This interface is read-only and cannot place orders.</footer>{help&&<ModelHelp strategy={help} onClose={()=>setHelp(null)}/>}</main>
}
